# Generated by Django 4.2.19 on 2025-02-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Admin', 'Admin')], default='Regular', max_length=7),
        ),
    ]
