# Generated by Django 4.2.19 on 2025-02-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='interests',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
